name: Deploy SokaFT api to VPS

on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup .NET 8
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: 8.0.x

            - name: Restore dependencies
              run: dotnet restore

            - name: Publish
              run: dotnet publish --output ./publish

            - name: Clean remote directory via SSH
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  script: find /home/jikai/soka -mindepth 1 -type f -not -name 'appsettings.json' -not -name 'soka.sqlite' -exec rm -f {} +

            - name: Deploy
              uses: appleboy/scp-action@v1
              with:
                  host: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  port: 22
                  source: './publish/*'
                  target: '/home/jikai/soka'
                  strip_components: 1

            - name: Restart soka service via SSH
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  script: sudo systemctl restart soka-api.service